shopware/shopware-cli

cmd/extension_zip.go
I just was going through the code and was at first quite confused :-D
=> chore: Rename variable to match behaviour

cmd/extension_zip.go
=> fix: Execute hooks in the temporary extension directory

cmd/extension/extension_prepare.go, cmd/extension/extension_zip.go, extension/config.go, extension/shopware-extension-schema.json, extension/zip.go
Fixes https://github.com/FriendsOfShopware/shopware-cli/issues/28
=> Feat: added excluded_packages to prepare step

.github/workflows/lint.yml
Go test works. 
@shyim 
For coverage reporting the secret dsn needs to be set in the gh actions env:
https://github.com/marketplace/actions/deepsource-test-coverage-action#:~:text=GitHub%20Action%20that%20enables%20you,repository%20for%20reporting%20to%20work.
=> WIP: CI: add go tests

cmd/extension/extension_build.go, cmd/extension/extension_zip.go
=> feat: Add possibility to specify SHOPWARE_PROJECT_ROOT

wiki/docs/commands/extension.md
=> update extension.md to add info about SHOPWARE_PROJECT_ROOT

.github/workflows/base-docker.yml, .github/workflows/go_test.yml, .github/workflows/lint.yml, .github/workflows/nix-update.yml, .github/workflows/release.yml, extension/app.go, extension/app_test.go, extension/platform.go, extension/platform_test.go
=> feat: add check for icon, fixes #123

flake.nix, go.mod, go.sum
=> fix: use fork with trigger fix

cmd/project/project_dump.go, flake.nix
=> feat: allow gzip compression on dump creation

extension/asset_platform.go
=> feat: improve 6.5 detection for assets

esbuild/esbuild.go, esbuild/util.go, esbuild/util_test.go
=> fix: technical name conversion, fixes #176

.devcontainer/devcontainer.json, wiki/docs/shopware-project-yml-schema.md
=> feat: add wiki entry for environment variable substitution

extension/asset_platform.go, extension/util.go, internal/esbuild/esbuild.go, internal/esbuild/util.go, internal/esbuild/util_test.go
with multiple uppercase characters in a row, closes #241
=> fix: kebab-case in asset names

extension/app_test.go, extension/asset_platform.go
- Fix: correct sw6.5 branch
- Move shopware/platform to shopware/shopware
=> Fix non existing sw65 branch

wiki/docs/commands/project.md
https://shopwarecommunity.slack.com/archives/C014X4KR2C8/p1706436465005849
=> chore: make anonymize-parameter more clear

cmd/project/project_admin_build.go, cmd/project/project_storefront_build.go
This was broken by 3b73c1e7c0954cbb038161bb3046b4e2d7fb12b0
=> Fix admin-build and storefront-build with no arguments

internal/esbuild/util.go, internal/esbuild/util_test.go
=> Fix technicalName in plugins.json

wiki/docs/shopware-extension-yml-schema.md
It was not immediately clear to me where to put this config file. I just guessed it. Maybe this helps someone.
=> Update shopware-extension-yml-schema.md to explain file location

extension/validator.go, extension/validator_test.go, internal/spdx/license.go, internal/spdx/license_test.go, internal/spdx/spdx-exceptions.json, internal/spdx/spdx-licenses.json
Implements SPDX license validation like happening in automated code-review
=> feat: Implement SPDX license validation and add test cases

cmd/project/platform.go, extension/asset_platform.go
Before:
Takes: ~6,7s
Downloads: 180MB
After:
Takes: ~4s
Downloads: 40MB
=> feat: use git sparse checkout to clone shopware

internal/changelog/changelog.tpl
AI Changelogs are removed in https://github.com/shopware/shopware-cli/commit/5d9ebdba2754d7126df29afc2ab0f2a06b1f527f
=> Remove unused ai generated messages template

internal/verifier/admintwiglinter/fix_text_field.go
I had broken code after conversion. With this the :value was converted correctly
=> Convert :value to v-model as well

internal/verifier/admintwiglinter/fix_text_field.go
I found it useful but I understand if this is not needed :) we likely can broaden it later to more fields
=> Remove values for attributes, that default to false and just need the attribute to be toggled

internal/verifier/twiglinter/storefronttwiglinter/link.go, internal/verifier/twiglinter/storefronttwiglinter/link_test.go
=> feat: implement LinkCheck linter for external links validation
