shopware/shopware-cli

- extension/zip.go
We are using a shared node_modules folder without splitting into administration and storefront - sounds legit, doesn't it?
Additionally, the folder `var` can just contain stuff you may not want :-) for example cs_fixer-cache.
> fix: add more defaultNotAllowedPaths for zip command

- .github/workflows/lint.yml
- .golangci.yml
Some lints get disabled automatically. This upsets the nolint lint.
Solution is to disable nolint lint for now
> Fix ci for go 1.18

- cmd/extension/extension_zip.go
- cmd/project/platform.go
Some version managers (in my case asdf) need a proper shell environment. This fixes the remaining environment replacements of command executions to keep the current environment.
> Keep OS environment intact for shell executions.

- cmd/extension/extension_create.go
- cmd/project/project_config_init.go
- cmd/project/project_extension_create.go
- config/config.go
Replicated the frosh:make:plugin command from FroshDevelopmentHelper to be able to create a new plugin skeleton without having the FroshDevelopmentHelper installed.
> Extension create - command

- cmd/extension/extension_create.go
The locale in the label section was wrong. It was en_GB, and should be en-GB
> Typo in locale for extension label

- .github/workflows/base-docker.yml
- .goreleaser.yaml
- Dockerfile
- Dockerfile.base
- scripts/entrypoint.sh
With this MR new base- and application images will be built for the PHP-versions v7.2, v7.4 and v8.1.
Also, the application image now contains the [node version manager](https://github.com/nvm-sh/nvm) as well as an entry point which utilizes it to set the node version in use according to `${NODE_VERSION}` (v18 by default).
> Make PHP and NodeJS versions configurable

- version/version.go
This allows extensions to use [`@stability` flags](https://getcomposer.org/doc/articles/versions.md#stability-constraints). Version constraints like `6.4-dev` are working already. This change should extend the capability to version constraints like `6.4@dev`.
Currently, when the `extension zip` subcommand encounters such a constraint in a `require` section of the `composer.json`, it throws this error:
```
FATA[0000] prepare package: add composer replacements: get shopware version constraint: Malformed constraint: 6.4@dev
```
I don't know, whether this was left out deliberately, so this PR might or might not make sense 😄
> Allow @stability flags

- version/version.go
And another one 😄 This allows version definitions for shopware packages to begin with any of `^ ~ v`, so `~6.4` would be valid then.
This is only useful for development purposes when working with a symlinked platform repository.
Before: https://regexr.com/76gc7
After: https://regexr.com/76gc1
> Adjust version regex prefix

- cmd/extension/extension_zip.go
When executing `extension zip`, the contents of the extension directory get copied over to `/tmp`.
At the moment, this is done for symlinks as well using the [shallow strategy](https://github.com/otiai10/copy/blob/main/options.go#L73). The symlinks, however, can't be zipped and lead to errors like this:
```
msg="create zip file: could not zip file, sourcePath: \"/tmp/extension1393500189/SwagPluginTemplate/vendor/shopware/core\", zipPath: \"SwagPluginTemplate/vendor/shopware/core\", read /tmp/extension1393500189/SwagPluginTemplate/vendor/shopware/core: is a directory"
```
This particular error could be solved by ignoring `shopware/[core, ...]` dependencies. However, skipping symlinks is a sensible approach when creating an archive either way.
> Ignore symlinks found in project directory when copying to /tmp

- .devcontainer/devcontainer.json
- .vscode/settings.json
- cmd/extension/extension_admin_watch.go
- cmd/extension/extension_build.go
- cmd/extension/extension_zip.go
- cmd/project/ci.go
- cmd/project/platform.go
- cmd/project/project_admin_build.go
- cmd/project/project_storefront_build.go
- extension/asset.go
- extension/asset_platform.go
- extension/asset_platform_test.go
- extension/asset_test.go
- extension/bundle.go
- extension/bundle_test.go
- extension/platform.go
- extension/project.go
- extension/root.go
- extension/zip.go
- internal/asset/source.go
- internal/esbuild/esbuild.go
- internal/esbuild/esbuild_test.go
In a project you need:
```json
{
"extra": {
"shopware-bundles": {
"src/MyBundle": {}
}
}
}
```
As an composer package, you need:
```json
{
"type": "shopware-bundle",
"extra": {
"shopware-bundle-name": "MyBundleName"
}
}
```
> feat: add bundle support

- extension/asset_platform.go
This PR lets `shopware-cli` detect what package manager was used based on the lock file. To then use that package manager to install dependencies. Currently, supported are `pnpm`, `yarn` and `npm` as a fallback.
> Detect and use package manger based on lock file

- shop/config.go
This would be nice e.g. for secrets that should not be committed in the configuration file. This would allow deploying configurations from github actions etc. via a secret store (e.g. github action secrets).
You could access them like this:
```
admin_api:
username: ${SHOPWARE_API_USERNAME}
password: ${SHOPWARE_API_PASSWORD}
```
Possible side effects are:
- Environment strings are now parsed and this could be problematic with some configurations where such strings or part of them (`${}`, `${SOME_VAR}`, `$SOME_VAR`) are willingly used as values
> feat: add support for environment variables in the project configuration

- .gitignore
- cmd/extension/extension_admin_watch.go
- cmd/project/ci.go
- extension/asset_platform.go
- extension/asset_platform_test.go
shopware-cli project ci builds right now all assets for any extension. The build system of the administration is stable, we can use the existing files of the extension. For the storefront we still need to do this.
Before: 46s
After: 18s
> feat(ci): build admin assets only needed

- cmd/project/ci.go
I noticed that in older Shopware versions like 6.4.11 `tecnickcom/tcpdf` is not directly required by `shopware/core`
> Check if tcpdf folder exists before trying to clean it

- cmd/extension/extension_build.go
- cmd/extension/extension_zip.go
- cmd/project/ci.go
- extension/asset.go
- extension/asset_platform.go
- extension/asset_platform_test.go
- extension/asset_test.go
- extension/project.go
- internal/asset/source.go
Right now `shopware-cli project ci` uses the traditional steps like `build-administration.sh` and `build-storefront.sh`
Since a while we support esbuild for building extensions much faster without access to the Shopware source code. To adopt this for building multiple extensions, we know split the extensions:
- ESBuild compatible admin/storefront now will always be build with esbuild.
- Any non-compatible extension will use the regular complication
So we have the best of both worlds. Some extensions build faster and which are not compatible use the regular setup.
Some benchmarks:
Project: All extensions have esbuild support. 
- `shopware project ci` (current version): 1 minute build time.
- `shopware project ci` (this branch): 29 seconds build time.
I think the improvement can be better …
> feat: use esbuild when possible for project builds

- cmd/project/project_dump.go
This is useful when using the project as part of a pipeline and much easier than trying to specify the correct null device path for each OS.
> Support database dump to stdout

- cmd/project/ci.go
- cmd/project/project_admin_build.go
- cmd/project/project_admin_watch.go
- cmd/project/project_storefront_build.go
- cmd/project/project_storefront_watch.go
- cmd/project/project_worker.go
- internal/phpexec/phpexec.go
- internal/phpexec/phpexec_test.go
Right now there is no easy way to choose a PHP version / installation for use by shopware-cli. This can be a problem when working on multiple projects with different required PHP versions.
Symfony's [CLI tool](https://github.com/symfony-cli/symfony-cli) can automatically detect the correct PHP version / installation to use for a project based on (among other things) a .php-version file or the required PHP version from composer.json files.
This PHP version can than be used by running `symfony php` instead of `php`. Similarly there is also a `symfony composer` command for running composer with the correct PHP version and even a `symfony console` command for running the `bin/console` tool.
We can use this to easily support different PHP versions.
This PR introduces a new `internal/phpexec` …
> Use symfony CLI for running PHP when available

- cmd/project/project_admin_build.go
- cmd/project/project_storefront_build.go
Using a relative directory for the PROJECT_ROOT given to node/webpack does not work. When manually specifying the path for `admin-build` or `project-build` this caused webpack to fail _for some of our developers_.
Not sure exactly why only for some, but using an absolute path always works.
> Fix webpack build with project dir argument

- cmd/account/account_producer_extension_info_pull.go
- cmd/account/account_producer_extension_info_push.go
- extension/config.go
- extension/shopware-extension-schema.json
Right now you have to describe inside the `.shopware-extension.yaml` each file you want to upload to the store, also if they are active in which language.
To simplify this, we introduce a new folder: `src/Resources/store/images` (it's configureable).
In this folder there are subfolders: `en`, `de` (both optional) and the images are all uploaded to that language, the first image sorted by file name is the preview one.
So it looks kinda this:
```
src/Resources/store/images/
├── de
│   ├── 0.png
│   ├── 1.png
│   └── 2.png (preview image)
└── en
├── 0.png
├── 1.png
└── 2.png (preview image)
```
The old way is still supported, but `info pull` will use the new format.
> feat: auto lookup images for extension images sync, fixes #317

- account-api/client.go
In some cases it could be possible that the cache directory doesn't exist until the process of storing the authentication token, especially in docker images. This pull request checks if the directory exists and creates it, if it not exists.
> Non existing cache directory occurs error

- account-api/client.go
Replace wrong method call Base() with Dir() while checking if the cache directory exists. :see_no_evil:
> Replace wrong method call Base() -> Dir()

- extension/zip.go
The timestamp of the built zip file was always 01.01.1980, 0:00, which may lead to opcache issues, because it caches also based on timestamps. Now current time is taken.
> fix: incorrect zip timestamp

- cmd/project/project_worker.go
This PR does a few things for the `shopware-cli project worker` command:
* Shopware messengers are terminated with SIGKILL when `shopware-cli` terminates
* SIGINT is now catched by the signal handler, so that you can ^C correctly
* There is a new option `--graceful-stop-limit`, which signals messengers with SIGTERM and waits for a specified amount of time before using SIGKILL. When PCNTL is available in the messengers, this allows the messenger to finish handling their last message. 
* Crashes of `shopware-cli` are now (mostly, hopefully) prevented by instead restarting the workers. This better handles situations where one messenger crashes for some reason, which previously detached all other messengers from `shopware-cli`, creating storms of messengers overloading systems
> fix: shopware messengers are orphaned on crash or SIGINT

- cmd/account/account_producer_extension_upload.go
- wiki/docs/commands/account.md
Flag `skip-for-review-result` is part of the `upload` but has been added to the parent command instead of the `upload` command. Therefore it is unusable
> fix: "skip for review result" flag on upload command

- cmd/project/project_admin_watch.go
When developing the application & env variables for prod are not available, running `shopware-cli project watch-admin` is not possible.
> fix(watch-admin): run framework:schema in current env

- wiki/docs/install.md
In my experience, it's more stable to just copy the binary from the upstream docker image. 
I also added a note about how to do it in a custom Docker image - even tho it's the same as in DDEV, I thought it makes sense to separate them due to the special file path in DDEV which.
> docs: install for docker without apt

- wiki/docs/commands/account.md
- wiki/docs/commands/extension.md
- wiki/docs/commands/project.md
- wiki/docs/shopware-extension-yml-schema.md
- wiki/docs/shopware-project-yml-schema.md
Some small copyright improvement
> Improve copy

- .github/workflows/release.yml
- .goreleaser.yaml
- Dockerfile.bin
- cmd/project/platform.go
- cmd/project/project_admin_build.go
- cmd/project/project_storefront_build.go
- extension/project.go
- **ci: add docker images on shopware namespace**
- **feat: use resolved apps/plugins from php, fixes #427**
> let php give extensions

- internal/changelog/changelog.go
- internal/changelog/changelog_test.go
This PR fixes changelog generation when no changelog template is specified. Previously it would set the default template too late in the process, resulting in broken links because the `VCSURL` variable was not set. 
This should resolve #438
> Fix changelog generation with default template

- cmd/project/ci.go
> fix: validate snippet filenames before reading & increase error verbosity

- extension/asset_platform.go
- internal/esbuild/util.go
- internal/esbuild/util_test.go
- internal/esbuild/vite_config.go
- internal/esbuild/vite_config_test.go
Dump expected vite config files for 6.7, so we can build forward compatible JavaScript files
> feat: implement Vite configuration dumping for asset compilation

- cmd/project/project_dump.go
Fixes #461
Add support for the --quick option in the project dump command.
* Add a new flag `--quick` to the `projectDatabaseDumpCmd` command.
* Pass the `--quick` option to the `database.NewMySQLDumper` function when the `--quick` flag is set.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/shopware/shopware-cli/pull/463?shareId=9f42c29f-6bd4-420e-b3fb-592b503b8882).
> Add --quick option to project dump command

- cmd/extension/extension_zip.go
- extension/config.go
Update the `ExtensionConfig` to set `validation.ignore` to `meta.setup` when `--overwrite-app-backend-secret` is passed to the zip command and dump the `.shopware-extension.yml` file again before zipping.
* Modify `cmd/extension/extension_zip.go` to adjust the `ExtensionConfig` and set `validation.ignore` to `meta.setup` when `--overwrite-app-backend-secret` is passed.
* Add logic to dump the `.shopware-extension.yml` file again before zipping when `--overwrite-app-backend-secret` is passed.
* Add a `Dump` method to the `Config` struct in `extension/config.go` to handle the dumping of the configuration to the `.shopware-extension.yml` file.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/shopware/shopware-cli/pull/473?shareId=1369d453-2cc …
> Fix zip command to adjust ExtensionConfig and dump .shopware-extension.yml

- internal/git/git_test.go
Improving the TestInvalidGitRepository by:
- Adding assertion for empty tag return value
- Adding explicit error assertion using testify
- Simplify the test suite by remove the error condition
> Enhance invalid git repository test assertions

- cmd/project/project_dump.go
Previously the code would double the port in the address since the `URL.Host` already contains the port.
> Fix DATABASE_URL handling

- cmd/project/project_dump.go
Fixes #480
Adjust the inner if condition in the project dump command to call `sprintf` only when the port is not set.
* Change the condition to check if the port is an empty string.
* Call `sprintf` to set `cfg.Addr` only when the port is not set.
* Set `cfg.Addr` to the host directly when the port is set.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/shopware/shopware-cli/pull/483?shareId=12e2e1f8-5210-4573-9e6f-f7353f184396).
> Fix condition in project dump command

- cmd/project/project_dump.go
- internal/git/git_test.go
- internal/phpexec/phpexec_test.go
- internal/phplint/download_test.go
- internal/phplint/lint_test.go
Replace `context.Background()` with `t.Context()` in various test functions to improve context handling.
* **internal/git/git_test.go**
- Replace `context.Background()` with `t.Context()` in `TestInvalidGitRepository`, `TestNoTags`, `TestWithOneTagAndCommit`, and `TestGetPublicVCSURL`.
- Remove unused `context` import statement.
* **internal/phpexec/phpexec_test.go**
- Replace `context.Background()` with `t.Context()` in `TestSymfonyDetection`.
- Add `context` import statement.
* **internal/phplint/download_test.go**
- Replace `context.Background()` with `t.Context()` in `TestDownloadPHPFile`.
* **internal/phplint/lint_test.go**
- Replace `context.Background()` with `t.Context()` in `TestLintTestData`.
---
For more details, open the [Copilot Workspace …
> Replace context.Background() with t.Context() in test files

- extension/zip.go
I just removed a failed (manual) code review, where a `.gitignore` file is located in `src/Resources/` :-)
This should remove the file also from subfolders.
> refactor: Remove `.gitignore` from all subfolders when packing a ZIP

- cmd/project/ci.go
- extension/asset_platform.go
- shop/config.go
- shop/shopware-project-schema.json
This PR implements the feature requested in issue #487 by adding a configuration option to enable admin builds for packages that distribute compiled files.
- Added a new `force_extension_build` configuration option to the `ConfigBuild` struct as a structured array of objects
- Updated `AssetBuildConfig` to include the `ForceExtensionBuild` field
- Modified asset platform logic to check if extensions are in the `force_extension_build` list before skipping builds
- Implemented a more extensible configuration format for future enhancements
Users can now configure extensions that should always be built, even if they have compiled files:
```yaml
build:
force_extension_build:
- name: SwagCommercial
```
This structured format allows for adding more configuration options to each extension in the …
> Add force_extension_build option for packages with compiled files

- extension/validator.go
fixes #492
I currently only implemented this for German texts. If we need this for other languages, I can add this as well.
> fix: count multibyte strings correctly

- extension/validator.go
Follow up for #493 as I forgot to also fix the length for the output.
> fix: consequent unicode strlen for german descriptions

- cmd/account/account_producer_extension_info_pull.go
- cmd/account/account_producer_extension_info_push.go
- extension/config.go
- extension/shopware-extension-schema.json
- internal/account-api/producer.go
- internal/account-api/producer_extension.go
- internal/changelog/changelog.go
- scripts/schema.go
This update introduces new fields for meta title and description in the extension configuration, allowing for better SEO and presentation in the store. The changes include:
- Added `MetaTitle` and `MetaDescription` fields to `ConfigStore`.
- Updated the account producer extension info pull and push commands to handle these new fields.
- Enhanced the `Extension` struct to include meta title and description for better data handling.
> feat: Add meta title and description support for extensions

- cmd/project/platform.go
- cmd/project/project_admin_build.go
- cmd/project/project_storefront_build.go
- cmd/root.go
closes #524
by cursor.AI
Adds a switch --only-custom-static-extensions to only build those plugins coming from custom/static-plugins and usually need to be built in dev
> feat: Add only-custom-static-extensions

- cmd/extension/extension_fix.go
This will improve the usage of the extension fix command when one is missing the argument. The argument was not listed by the help instruction so it was easy to forget.
> Ensure cobra can validate the need for the path argument by adding more command info

- internal/html/parser.go
- internal/html/testdata/39-attributes-escaped-content.txt
- internal/verifier/admintwiglinter/fix_select_field_test.go
When one has quotes in attribute values the output HTML is not understood by different tools. So I start to escape quotes. This is important for other pull requests I will make :D
> Ensure HTML attributes escape quotes to prevent syntax errors

- cmd/project/project_image_proxy.go
- shop/config.go
- shop/shopware-project-schema.json
- Adds a new `shopware-cli project image-proxy` command that starts an HTTP server to serve files from the local `public` folder with fallback to a remote upstream server
- Automatically caches remote files locally to improve performance and reduce bandwidth usage
- Integrates seamlessly with Shopware by automatically configuring the filesystem adapter
- **Local-first serving**: Checks local `public` folder first before proxying to upstream
- **File caching**: Caches remote files in `var/cache/image-proxy/` with preserved Content-Type headers
- **Simple cache design**: No TTL or complex eviction - just stores files until manually cleared
- **Gzip compression**: Automatically compresses responses for text-based content types
- Upstream URL can be configured in `.shopware-project.yml`: …
> feat: image proxy for projects

- shop/config.go
- shop/config_test.go
Having the following configurations:
File: **shopware-project.staging.yml**
```yaml,.shopware-project.staging.yml
url: https://xyz.nuonic.dev
include:
- .shopware-project.base.yml
sync:
config:
- settings:
core.store.licenseHost: xyz.nuonic.dev
```
File: **shopware-project.base.yml**
```yaml,.shopware-project.base.yml
admin_api:
client_id: ${SHOPWARE_CLI_CLIENT_ID}
client_secret: ${SHOPWARE_CLI_CLIENT_SECRET}
dump:
where:
customer: "email LIKE '%@nuonic.de' OR email LIKE '%@xyz.com'"
nodata:
- promotion
- promotion_cart_rule
- promotion_discount
- promotion_discount_prices
- promotion_discount_rule
- promotion_individual_code
- promotion_order_rule
- promotion_persona_customer
- promotion_persona_rule
- promotion_sales_channel
- promotion_setgroup
- promotion_setgroup_rule
- …
```
> fix(project): change config merge priority

- cmd/extension/extension_zip.go
- extension/zip.go
- extension/zip_test.go
in the generation of the checksum.json file
> fix: Do not fail ZIP file generation if extension version cannot be determined

- cmd/project/project_admin_build.go
- cmd/project/project_admin_watch.go
- cmd/project/project_storefront_build.go
- cmd/project/project_storefront_watch.go
I added some aliases which come in handy in daily use. Origin of this change is my own inability to memorize which way around these commands go.
As I think others might be as stupid as me, have a look :)
> feat(commands): add common aliases to project commands

- cmd/account/account_producer_extension_upload.go
While trying to release a new version of Commercial, the Code-Review got stuck and shopware-cli got into the Code Review timeout.
I just got the output "Skipping waiting for code review result as it took too long" and the workflow got stuck.
I think we need to break out of the `for` at that point.
> fix: break out of code review loop on retry skip

- cmd/project/project_validate.go
- internal/validation/reporter.go
- internal/validation/reporter_test.go
This adds a reporter for Gitlab CI, including autodetection of execution within Gitlab CI.
> feat: add gitlab CI codequality integration
